import java.text.SimpleDateFormat

task copyInfo(type: Copy) {
    from('src/main/resources') {
        include 'product-info.properties'
        include 'plugin.yml'
    }
    into 'build/resources/main'
    // 禁用up-to-date检查
    outputs.upToDateWhen { false }
}

tasks.processResources.dependsOn(copyInfo)

def expandFiles = Set.of(
        '**/*.product-meta.json',
        '**/product-info.properties',
        '**/plugin.yml'
)

def expandProps = [
        'version'   : project(":starlight-bukkit-core").property("version"),
        'build_time': new SimpleDateFormat("YYYY-MM-dd HH:mm:ss").format(new Date())
]

processResources {
    doFirst {
        filesMatching(expandFiles) {
            expand(expandProps)
        }
    }
}