import java.text.SimpleDateFormat

task copyInfo(type: Copy) {
    from('src/main/resources') {
        include 'product-info.properties'
        include 'plugin.yml'
    }
    into 'build/resources/main'
    // 禁用up-to-date检查
    outputs.upToDateWhen { false }
}

tasks.processResources.dependsOn(copyInfo)

def version() {
    var pv = project(":starlight-core").property("version")

    return pv
}


processResources {
    doFirst {
        filesMatching('**/*.product-meta.json') {
            expand([
                    'version'   : version(),
                    'build_time': buildTime()
            ])
        }
        filesMatching("**/plugin.yml") {
            expand([
                    'version': version()
            ])
        }
    }
}

