rootProject.name = 'Starlight-plugin'

//include 'starlight-game'
//include 'starlight-extensions:starlight-ext-lobby'
//include 'starlight-extensions:starlight-ext-ai'
//include 'starlight-extensions:starlight-ext-plot'
//include 'starlight-extensions:starlight-ext-worldguard'
//include 'starlight-basic'
//include 'starlight-bundler'
//include 'starlight-extensions:starlight-ext-music'
//include 'starlight-adventure-loader'

include 'starlight-core'

include 'starlight-bukkit-core'
include 'starlight-bukkit-bundler'

include 'starlight-velocity'
