apply from: rootDir.getAbsolutePath() + "/gbuild.gradle"

applyGlobalScript("Publish/MinecraftServerTest.gradle")
applyGlobalScript("Publish/ProjectOutput.gradle")
applyGlobalScript("Repo/MinecraftPlugins.gradle")
applyGlobalScript("Dependencies.gradle")

//platform libraries
dependencies {
    compileOnly 'org.jetbrains:annotations:24.0.0'
    compileOnly 'net.kyori:adventure-api:4.17.0'

    compileOnly gbuildLib('me.gb2022.commons:commons-nbt')
    compileOnly gbuildLib('me.gb2022.commons:commons-math')
    compileOnly gbuildLib('me.gb2022.commons:commons-container')
    compileOnly gbuildLib('me.gb2022.commons:commons-general')
    compileOnly gbuildLib('me.gb2022.commons:commons-event')
    compileOnly gbuildLib('me.gb2022.commons:commons-reflection')
    compileOnly gbuildLib('me.gb2022.commons:commons-compatibility')

    compileOnly 'org.mongodb:bson:5.6.0'

    compileOnly gbuildLib('org.atcraftmc.qlib:qlib-bukkit')
    compileOnly gbuildLib('me.gb2022.apm:apm-remote')
    compileOnly gbuildLib('me.gb2022.apm:apm-plugin')
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

//api
dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
    compileOnly 'io.netty:netty-buffer:4.1.25.Final'

    compileOnly project(":starlight-core")
    compileOnly project(":lib-starlight-shared")
    compileOnly gbuildLib("me.gb2022:gluon-main")
}

apply from: rootDir.getAbsolutePath() + "/info.gradle"

tasks.named('build').get().dependsOn(':starlight-core:build')