config:
  music-service:
    remote: /{$proxy}
    cdn-server: lobby
    pitch-offsets:
      "Kiss_The_Rain.mid": -1
  music-player:
    mount: false #whether to play on entity or on entity location.
    ui: "{#white}{msg#playing} {#yellow}: {#aqua}{name} {#yellow}|{#white} {time}{#gray} / {#white}{total}"
  music-game:
    edit-mount: "world:50,0,0"
    ui: "{#white}{msg#playing}: {#aqua}{name} {#yellow}| {#white}{time}{#gray} / {#white}{total} {#yellow}| {#white}{msg#notes}: {#purple}{notes}{#white}/{#dark-purple}{total-notes}"