plugins {
    id 'java'
}

apply from: '../../starlight-package.build.gradle'

repositories {
    maven { url = 'https://maven.enginehub.org/repo/' }
}


dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    compileOnly 'com.sk89q.worldedit:worldedit-bukkit:7.2.0-SNAPSHOT'
    compileOnly 'com.sk89q.worldedit:worldedit-core:7.2.0-SNAPSHOT'

    compileOnly projectLib("worldguard-bukkit-7.1.0-20220312.223410-2")
    compileOnly projectLib("worldguard-core-7.1.0-20220312.223410-2")
}

test {
    useJUnitPlatform()
}