plugins {
    id 'java'
}

apply from: "../gbuild.gradle"

applyGlobalScript("Publish/ProjectOutput.gradle")

group = 'org.atcraftmc'

repositories {
    papermcRepo()
}

dependencies {
    compileOnly 'net.kyori:adventure-api:4.17.0'
    compileOnly 'org.mongodb:bson:5.6.0'

    compileOnly projectLib('bukkit-configurations-api')

    compileOnly gbuildLib('me.gb2022.commons:commons-nbt')
    compileOnly gbuildLib('me.gb2022.commons:commons-math')
    compileOnly gbuildLib('me.gb2022.commons:commons-container')
    compileOnly gbuildLib('me.gb2022.commons:commons-general')
    compileOnly gbuildLib('me.gb2022.commons:commons-event')
    compileOnly gbuildLib('me.gb2022.commons:commons-reflection')


    compileOnly gbuildLib("me.gb2022.apm:apm-remote")
    compileOnly gbuildLib("me.gb2022.apm:apm-plugin")

    compileOnly gbuildLib("me.gb2022:gluon-main")
    compileOnly gbuildLib("org.atcraftmc.qlib:qlib-base")

    //compileOnly "org.rocksdb:rocksdbjni:8.11.3"
    compileOnly 'io.netty:netty-buffer:4.1.100.Final'
    compileOnly 'com.google.code.gson:gson:2.13.2'

    compileOnly "org.apache.logging.log4j:log4j-api:2.8.1"
    compileOnly 'com.google.guava:guava:31.0.1-jre'
}