config:
  proxy-motd:
    sync: true #sync=false: use local motd
    sync-target: lobby
    sync-interval: 1000 #millseconds
    overwrite-version: true #use version from synced ping
    overwrite-player-count: true #use all players on proxy
    overwrite-player-max: 2026 #set -1 to use value synced
    overwrite-text: true #apply some proxy-dedicated process to motd
    text-rewrites:
      example: "Yay im a rewrite replacing {{example}} to me"
    player-prompt:
      - "{#aqua}在线人数: {#white}{node} {#gray}/ {#white}{all}"
      - "{#gray}全局玩家数量: {#white}{all}"
      - "{#gray}全局玩家上限: {#white}{all-cap}"
      - "{#gray}节点玩家数量: {#white}{node}"
      - "{#gray}节点玩家上限: {#white}40"
  hub-command:
    server: lobby #default server id.
  tab-sync:
    format: "{#gold}[{#reset}{}{#gold}]{#gray}{}"
  chat-sync:
    template: "{#gold}[{#reset}{}{#gold}]{#white}{}: "
  server-transfer-message:
    broadcast-global: true