plugins {
    id 'java'
}

group = 'me.gb2022'
version = 'unspecified'

apply from: rootDir.getAbsolutePath() + "/gbuild.gradle"

applyGlobalScript("Publish/ProjectOutput.gradle")

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":starlight-core")
    implementation project(":starlight-basic")
    implementation project(":starlight-game")
    implementation project(":starlight-extensions:starlight-ext-music")
    //todo: add lobby
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}