plugins {
    id 'java'
}

group = 'me.gb2022'
version = 'unspecified'

apply from: rootDir.getAbsolutePath() + "/gbuild.gradle"
apply from: rootDir.getAbsolutePath() + "/info.gradle"

applyGlobalScript("Publish/ProjectOutput.gradle")

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":starlight-core")
    implementation project(":starlight-basic")
    implementation project(":starlight-game")
    implementation project(":starlight-extensions:starlight-ext-music")
    implementation project(":starlight-extensions:starlight-ext-worldguard")
    implementation project(":starlight-extensions:starlight-ext-lobby")
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('build').get().dependsOn(':starlight-core:build')
tasks.named('build').get().dependsOn(':starlight-basic:build')
tasks.named('build').get().dependsOn(':starlight-game:build')
tasks.named('build').get().dependsOn(':starlight-extensions:starlight-ext-music:build')
tasks.named('build').get().dependsOn(':starlight-extensions:starlight-ext-lobby:build')

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}