config:
  realistic-sleep:
    scale-per-player: 3.5
    health-interval: 20
    health-amount: 1
  vein-miner:
    max-iterations: 64
    regex: "_ore|_leaves|_log|glowstone|ancient_debris"
  extra-damage:
    extra-damage: {}
    percent-damage:
      tacz:modern_kinetic_gun: 0.05
  item-drop-secure:
    unlock-time: 120
    list:
      - "diamond_"
      - "netherite_"
      - "nether_star"
      - "iron_boots"
      - "iron_leggings"
      - "iron_chestplate"
      - "iron_helmet"
      - "iron_pickaxe"
      - "elytra"
      - "iron_axe"
      - "iron_shovel"
      - "iron_sword"
      - "iron_hoe"
      - "golden_"
      - "gold_"
  realistic-minecart:
    ui: '{run-mode}{#white}({msg#level}{level}) {#yellow}|{#white} {msg#speed}{speed} {#yellow}|{#white} {msg#acceleration}{acceleration}m/s^2'
    max-speed: 1.5
    safety-speed: 0.5
    auto-align: false
    thrust-1-acceleration: 0.08
    thrust-2-acceleration: 0.16
    thrust-3-acceleration: 0.27
    thrust-4-acceleration: 0.32
    thrust-0-acceleration: 0
    thrust--1-acceleration: -0.08
    thrust--2-acceleration: -0.29
    thrust--3-acceleration: -0.32
    thrust--4-acceleration: -0.5