config:
  ip-defender:
    service: "baidu" #optional value: baidu|ip-api|pconline|real-ip
    record: true #是否记录IP属地变化
    auto-ban: false #是否自动封禁
    auto-ban-day-time: 0 #封禁的时间，往下为天，时，分，秒
    auto-ban-hour-time: 0
    auto-ban-minute-time: 10
    auto-ban-second-time: 0
  explosion-defender:
    smart-cancel: true
    override-explosion: false
    record: true
    broadcast: true
  permission-manager:
    default-group: --player
  guest-mode:
    affect-world: [ ]
  we-operation-defender:
    warn-stack-length: 64
    warn-selection-size: 128
    warn-stack-effect-size: 384
    max-selection-size: 128
    max-edit-size: 384
  item-defender:
    record: true #是否记录
    broadcast: false #是否广播给管理员
    op-ignore: true #OP是否可以豁免
    illegal-list: #没收的列表(注: 其中填写 Minecraft ID)
      - "projecte:rm_morning_star"
      - "projecte:rm_sward"
      - "projecte:rm_katar"
    warning-list: #发出警告的列表
      - "minecraft:tnt"
      - "minecraft:flint_and_steel"
      - "minecraft:lava_bucket"