config:
  dynamic-view-distance:
    max: 32
    calc-period: 100000
  position-align:
    fix-spawn-position: true
  surrounding-refresh:
    update-on-explode: false
  freecam:
    anti-cheat: true
  menu-item:
    item: 'minecraft:clock'
    bind-command: 'menu'
    detect-join: true
    detect-respawn: false
    detect-drop: true