config:
  disabled-service:
    values: #disable service(will be rejected)here
      - http-service
      - remote-message-service
  smtp-service: #general SMTP configuration
    server: smtp.example.com:465 #address and port
    username: ExampleUser #user
    password: ExamplePassword #password
  http-service: #where holds all http services
    host: 127.0.0.1 #bind address
    port: 8125 #bind port
    backlog: 10 #ref:sun.http.httpserver->backlog
    threads: 3
  locale:
    join-delay: 20 #time before recalculate player's locale
    as-control: true
  player-view-customization:
    ui-template:
      - "{#white}{desc}"
      - " "
      - "{msg#ui-state-{state}}"
      - "{msg#ui-click}"
      - " "
      - "{#gray}id: {id}"
      - "{#gray}prov: {provider}"